### ISSUE TITLE
duda

### ISSUE THREAD

**Issue by abelnexus** [stoner6593/Factura-2.1#2]
disculpa pero como creo el archivo xml ? al darle click en boleta,factura,nota de debito o credito no ocurre nada, solo se minimiza y ya no me dejar dar click sobre ningun otro  boton

**Comment by stoner6593** [comment]
El proceso es simple, Debes dar click en Factura, Boleta, NC o ND según requieras, luego dar click en fimar, y para finalizar le das en Enviar documento...
